### ISSUE TITLE
Failed to get IPTS device info from driver

### ISSUE THREAD

**Issue by LostMiracle94** [Xiashangning/IPTSDaemon#1]
I ran the install, everything copied in right places. Rebooted, nothing. launched iptsdaemon and get this: 

[12:54:04.480] [error] Failed to get IPTS device info from driver

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

Also I hope it was just typo but I have latest Bigsurface 6.4 not 6.5 as readme states. Surface pro7 i5 126gb 8gb ram

**Comment by Aphcity** [comment]
how did you fix it

**Comment by calebtb06** [comment]
Anyone else have this issue manage to fix it?
