### ISSUE TITLE
Can´t install IPTSDaemon on SP7 with Monteray

### ISSUE THREAD

**Issue by Peterro61** [Xiashangning/IPTSDaemon#1]
If I run "install_daemon.sh " in Terminal itś stop with Mistakes 
cp: IPTSDaemon: No such file or directory
chmod: /usr/local/bin/IPTSDaemon: No such file or directory
chown: /usr/local/bin/IPTSDaemon: No such file or directory
cp: ipts_config: No such file or directory
cp: com.xavier.IPTSDaemon.plist: No such file or directory

Can you please tell me how to do that right? Thanks

**Comment by Xiashangning** [comment]
You need to ENTER that folder, eg. `cd path_to_IPTSDaemon_folder`
then run this script.

**Comment by Xiashangning** [comment]
emm, that's all? If you touch the screen, there is no other output? At least there should be something like "Enter d0i3 mode"
Does your touchscreen work fine in Windows?

**Comment by Peterro61** [comment]
Product = Surface Touch Screen
ProductID = 0x99f
On Windows the touchscreen worked, but now I don't have Windows installed
