### ISSUE TITLE
尝试了很多次以后IPTSDaemon仍然不起作用

### ISSUE THREAD

**Issue by Qiange7780** [Xiashangning/IPTSDaemon#11]
您好大神，我已经更新了Bigsurface和IPTSDaemon 1.2，但是触摸屏仍然不起作用，我最近参考了一些完成和未完成的lssues，曾尝试手动启动，启动后显示如下结果

**Comment by Qiange7780** [comment]
Last login: Sun Jul 31 10:58:54 on ttys000
/usr/local/bin/IPTSDaemon ; exit;
surface@localhost ~ % /usr/local/bin/IPTSDaemon ; exit;
dyld[1653]: Library not loaded: '/usr/local/opt/inih/lib/libinih.0.dylib'
  Referenced from: '/usr/local/bin/IPTSDaemon'
  Reason: tried: '/usr/local/opt/inih/lib/libinih.0.dylib' (no such file), '/usr/lib/libinih.0.dylib' (no such file)
zsh: abort      /usr/local/bin/IPTSDaemon

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[进程已完成]

**Comment by Qiange7780** [comment]
对了我的机型是i7 1065G7，使用的是您i5的EFI，我修改了机型配置和三码，其他的我并没有修改，但能顺利进入系统，目前12.5系统方面使用没有任何问题，不知道是否和EFI有关

**Comment by Xiashangning** [comment]
你看一下README的安装步骤啊

**Comment by Xiashangning** [comment]
要安装inih和fmt两个库

**Comment by Qiange7780** [comment]
谢谢大神，英语学的不太好，一开始没有看明白步骤，现在问题解决了，触摸情况良好，根据后面的步骤也成功实现了用笔防误触和开机屏幕键盘，现在就是使用过程中触屏会时常跳动，不过还是感谢大神的努力和研究，使得触摸屏成为可能，期待后续新版本

**Comment by 123MEMZ** [comment]
hxd，你知道用笔防误触啥的是修改哪个文件呀，我没找到😂
