### ISSUE TITLE
[error] Could not find IntelPreciseTouchStylusDriver 

### ISSUE THREAD

**Issue by MEIZU16** [Xiashangning/IPTSDaemon#12]
device: surface laptop 3
os: Monterey 12.1

/Users/hutao/Downloads/IPTSDaemon/IPTSDaemon ; exit;                            
hutao@192 ~ % /Users/hutao/Downloads/IPTSDaemon/IPTSDaemon ; exit;
[17:13:25.254] [error] Could not find IntelPreciseTouchStylusDriver!: No such file or directory

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[进程已完成]

hutao@192 ~ % sudo dmesg | grep -E "SurfaceS|SurfaceH|SurfaceM|IntelP"
Password:
[  372.556398]: Disabling CS_ENFORCEMENT for entitled process.Disabling CS_ENFORCEMENT for entitled process.Sandbox: com.apple.WebKit(918) deny(1) mach-lookup com.apple.mobileassetd.v2tcp_timers: tcp_output() returned 0 with retransmission timer disabled for 49551 > 50098 in state 4, reset timer to 1069SurfaceSerialHubDriver::data length error!
[  376.682181]: SurfaceSerialHubDriver::msg dump: length: 42
[  376.682216]: SurfaceSerialHubDriver::aa 55 00 26 00 0c 2a 71 80 15 00 02 03 15 00 00 
[  376.682227]: SurfaceSerialHubDriver::04 03 87 02 0e 05 07 e1 03 42 04 0b db 04 67 03 
[  376.682237]: SurfaceSerialHubDriver::0f 0b 06 3e 03 00 00 00 00 00 00 00 00 00 00 00 
[  376.689684]: SurfaceSerialHubDriver::Message received incomplete! Protential data loss!
[  376.689706]: SurfaceSerialHubDriver::msg dump: length: 6
[  376.689713]: SurfaceSerialHubDriver::aa 55 04 00 29 3f 00 00 00 00 00 00 00 00 00 00

**Comment by Xiashangning** [comment]
You need to install `DebugEnhancer.kext` then attach the output of this command

**Comment by Xiashangning** [comment]
have you solved it？

**Comment by MEIZU16** [comment]
> have you solved it？

我发现我用的是1.0.4的bigsurface，如果使用最新版的话键盘触摸板无法使用

**Comment by Xiashangning** [comment]
你试一下这个
https://github.com/Xiashangning/BigSurface/files/9247532/BigSurface.kext.zip

**Comment by MEIZU16** [comment]
> 你试一下这个 https://github.com/Xiashangning/BigSurface/files/9247532/BigSurface.kext.zip 这个测试版驱动加上正式版附带的ssdt

ssdt用oca直接添加到config.plist就可以吗，另外我也没看见SSDT_ALS0.aml这个文件。使用这个驱动还是不行。

**Comment by Xiashangning** [comment]
怎么个不行法，是无法启动，还是触摸板键盘没反应

**Comment by MEIZU16** [comment]
触摸板键盘没反应

**Comment by Xiashangning** [comment]
我需要终端sudo dmesg | grep -E 'SurfaceS|SurfaceB|SurfaceM|SurfaceH|IntelP' 的输出，记得DebugEnhancer驱动装上
还有ioreg，就是ioregisteryexplorer保存的文件

**Comment by MEIZU16** [comment]
[ioreg.zip](https://github.com/Xiashangning/IPTSDaemon/files/9252372/ioreg.zip)
使用该驱动的输出信息没办法提供。。因为无法使用键盘，包括外接的
下面是使用1.0.4的输出
hutao@192 ~ % sudo dmesg | grep -E 'SurfaceS|SurfaceB|SurfaceM|SurfaceH|IntelP' 
Password:
[    0.400368]: SurfaceButtonDriver::Found valid GPIO interrupts
[    0.400375]: SurfaceButtonDriver::Surface ACPI button device found!
[    0.400382]: SurfaceButtonDriver:0x100000284 start
[    0.400423]: SurfaceSerialHubDriver::Found valid UART Bus!
[    0.400617]: SurfaceButtonDriver::Got GPIO Controller! VoodooGPIOIceLakeLP
[    0.439764]: SurfaceSerialHubDriver::Got UART Controller! VoodooUARTController
[    0.500831]: SurfaceButtonDevice:0x100000333 start
[    0.500956]: SurfaceButtonDriver::Woke up
[    0.500963]: SurfaceButtonDevice:0x100000333 message: 0xe0000230 from: 0x100000284 0
[    0.501379]: SurfaceButtonDevice:0x100000333 creating interfaces
[    0.540779]: SurfaceSerialHubDriver::Surface Serial Hub found!
[    0.543249]: SurfaceSerialHubDriver::SAM version 14.502.139
[    0.543274]: SurfaceSerialHubDriver::Surface Battery nub published!
[    0.543315]: SurfaceBatteryNub::Woke up
[    0.545881]: SurfaceBatteryDriver::Plugin submitted
[    0.545887]: SurfaceBatteryDriver::Set performance mode to 1
[    0.545896]: SurfaceBatteryDriver::Woke up
[    0.548216]: SurfaceSerialHubDriver::Surface Laptop3 nub published!
[    0.567259]: SurfaceSerialHubDriver::Woke up
[    0.665087]: SurfaceSerialHubDriver::Warning, given buffer_len(60) and received data_len(2) mismatched!
[    4.949485]: SurfaceButtonDevice:0x100000333 Matching has vendor DeviceUsagePage : ff0c bundleIdentifier com.apple.AppleUserHIDDrivers ioclass AppleUserHIDEventService but transport and vendorID is missing
[    5.124447]: SurfaceButtonDevice:0x100000333 Matching has vendor DeviceUsagePage : ff0c bundleIdentifier com.apple.AppleUserHIDDrivers ioclass AppleUserHIDEventService but transport and vendorID is missing
[    6.754166]: Sandbox apply: com.apple.AmbientDisplayAgent[305] <bytes>1 duplicate report for Sandbox: bluetoothd(147) deny(1) file-read-data /Library/Preferences/com.apple.networkd.plistSandbox: bluetoothd(147) deny(1) file-read-metadata /Library/Application SupportSandbox: bluetoothd(147) deny(1) file-read-metadata /Library/Application Support/BTServerSandbox: com.apple.AmbientDisplayAgent(305) deny(1) mach-lookup com.apple.windowserverSandbox apply: searchpartyd[307] <bytes>1 duplicate report for Sandbox: com.apple.AmbientDisplayAgent(305) deny(1) mach-lookup com.apple.windowserverSandbox: locationd(133) deny(1) mach-lookup com.apple.tccdSandbox: locationd(133) deny(1) mach-lookup com.apple.tccd.systemSandbox: locationd(133) deny(1) mach-lookup com.apple.tccdSandbox: locationd(133) deny(1) mach-lookup com.apple.tccd.systemSandbox: bluetoothd(147) deny(1) mach-lookup com.apple.biome.access.systemSandbox: bluetoothd(147) deny(1) mach-lookup com.apple.biome.compute.source.userSurfaceButtonDevice:0x100000333 message: 0xe0000101 from: 0x100000284 1
hutao@192 ~ %

**Comment by MEIZU16** [comment]
对了，我现在系统升级到了13beta

**Comment by Xiashangning** [comment]
1.0.4的没用。。。外接usb键盘和这个驱动没有任何关系啊，为什么不能用

**Comment by Xiashangning** [comment]
试试这个
[BigSurface.kext.zip](https://github.com/Xiashangning/IPTSDaemon/files/9256402/BigSurface.kext.zip)

**Comment by MEIZU16** [comment]
牛啊dalao，这个可以正常使用了。（外接键盘用不了是我自己驱动的问题）

**Comment by Xiashangning** [comment]
OK，帮我再测试一下这个版本，确认没有问题就发布了
[BigSurface.kext.zip](https://github.com/Xiashangning/IPTSDaemon/files/9256974/BigSurface.kext.zip)

**Comment by MEIZU16** [comment]
> OK，帮我再测试一下这个版本，确认没有问题就发布了 [BigSurface.kext.zip](https://github.com/Xiashangning/IPTSDaemon/files/9256974/BigSurface.kext.zip)

没问题，可以正常使用

**Comment by Xiashangning** [comment]
ok
