### ISSUE TITLE
losing surface-pro-7.conf

### ISSUE THREAD

**Issue by kevin-Curry** [Xiashangning/IPTSDaemon#12]
That's a big problem!!!
in version 1.4 presets losing surface-pro-7.conf
So only 1.3 can drive the touchscreen

**Comment by WEEZOOKARP** [comment]
where is 1.3?

**Comment by Xiashangning** [comment]
That is because the config file is `iptsd.conf` for all devices now. In `presets` folder there are only device related parameters (screen res etc.) for older devices. You should change the settings in `iptsd.conf`
