### ISSUE TITLE
Scroll with one finger possible (when using touch screen)?

### ISSUE THREAD

**Issue by sergeykoznov** [Xiashangning/IPTSDaemon#13]
I wound love to modify two finger scrolling to one? is this possible? and one more, I want to disable touch when palm but don't know location of my device's config file? thanks! I found this app which in Scroll 2 (https://ryanhanson.dev/scroll) but this app with touch screen won't work :-(

**Comment by Xiashangning** [comment]
> I wound love to modify two finger scrolling to one? is this possible?

Technically speaking, this is possible, but how are you going to define the `drag` operation ? As well as `selecting` texts, etc.

> I want to disable touch when palm but don't know location of my device's config file?

You can check the `ipts_config` folder, add it to your device's file and then reinstall. Or go to `/usr/local/ipts_config`

**Comment by sergeykoznov** [comment]
awesome. thanks!
