### ISSUE TITLE
Cannot get it to work. Referencing the library version 8 instead of the latest 9 one.

### ISSUE THREAD

**Issue by WathitdewRecord** [Xiashangning/IPTSDaemon#14]
Hi, I am not able to make this work even after doing all of the steps. here what it show me.

/usr/local/bin/IPTSDaemon ; exit;
wathitdewrecord@SurfacePro6MacOS ~ % /usr/local/bin/IPTSDaemon ; exit;
dyld[771]: Library not loaded: '/usr/local/opt/fmt/lib/libfmt.8.dylib'
  Referenced from: '/usr/local/bin/IPTSDaemon'
  Reason: tried: '/usr/local/opt/fmt/lib/libfmt.8.dylib' (no such file), '/usr/local/lib/libfmt.8.dylib' (no such file), '/usr/lib/libfmt.8.dylib' (no such file), '/usr/local/Cellar/fmt/9.0.0/lib/libfmt.8.dylib' (no such file), '/usr/local/lib/libfmt.8.dylib' (no such file), '/usr/lib/libfmt.8.dylib' (no such file)
zsh: abort      /usr/local/bin/IPTSDaemon

It say libfmt.8.dylib is not there but I think it is normal it is now version 9. Can someone help me please, thank you very much.

**Comment by balopez83** [comment]
I believe this will need to be recompiled using the new FMT 9.0.0 released under brew a few days ago. I tried everything I could think of to find a way to install the old version of FMT but it just doesn't seem to work unless you already had it. Personally I am going to attempt to recompile this under Xcode and see if I can make it work though expect we will need for this to be officially updated.

**Comment by WathitdewRecord** [comment]
That make a lot of sense thank you very much for the response. I guess im going to wait for the update but if you get it to work just dm me or something. Have a wonderful day! :D

**Comment by WathitdewRecord** [comment]
> I believe this will need to be recompiled using the new FMT 9.0.0 released under brew a few days ago. I tried everything I could think of to find a way to install the old version of FMT but it just doesn't seem to work unless you already had it. Personally I am going to attempt to recompile this under Xcode and see if I can make it work though expect we will need for this to be officially updated.

Where you successfull at making it work?

**Comment by balopez83** [comment]
Hi @WathitdewRecord, unfortunately I have not yet been able to get it to work. Hopefully @Xiashangning can get this updated to use FMT 9.0.0 when time allows. I will keep trying but I am not optimistic that I will be able to resolve it on my own.

**Comment by Xiashangning** [comment]
Hi guys, the code is updated and you can use the new release.

**Comment by balopez83** [comment]
Thank you @Xiashangning for updating the code so quickly. You have done some amazing work getting the Surface devices working so well where others haven't been able.
