### ISSUE TITLE
关于macOS触屏虚拟键盘的问题

### ISSUE THREAD

**Issue by 123MEMZ** [Xiashangning/IPTSDaemon#17]
大佬您好，我已按照您安装说明的步骤成功安装上了触屏驱动！～
但现在有一个问题：我在使用macOS上的虚拟键盘的过程中，但凡我敲键盘敲的稍微快了一点，那个键就会重复输入好几遍，所以我想来咨询一下是不是通病🤝（如下图所示，就比如“ji iia hao”，中间会多加两个i，有时候不止两三个，四五个都有可能）

![image](https://user-images.githubusercontent.com/97831256/204156182-f5202080-7de3-4b30-99b0-5bbb75f65508.png)

**Comment by 123MEMZ** [comment]
不过我搜索了好久，也去csdn上找了，似乎没有人提过这个🤔

**Comment by Xiashangning** [comment]
这个问题不清楚。不过触摸识别的代码现在还没有很好地优化，可能会有瞬发的卡顿，然后造成了这样

**Comment by 123MEMZ** [comment]
好的！辛苦了！期待早日优化～
