### ISSUE TITLE
Wake IPTSDaemon after sleep

### ISSUE THREAD

**Issue by plsh2me** [Xiashangning/IPTSDaemon#2]
Hi, As per instruction I installed the IPTSDaemon, Homebrew and dylib's. 
So touchscreen works as expected, but after sleep its not working. 
I don't know if I did something wrong to create the sleep and wakeup files. I just ran the command to the Documents file (as you can see the picture). And checked the touchscreen not works after sleep. 
Will you please specify the best place (folder) for this and provide the details of installation command?
<img width="667" alt="Screenshot 2022-06-29 at 23 01 27" src="https://user-images.githubusercontent.com/24899438/176553802-a4d7f606-4e6d-4fee-9772-80009dfeaa01.png">

**Comment by Xiashangning** [comment]
There is no 'best' folder, just THE folder: your home folder (AKA: the parent folder of your current folder in the picture), I've updated the instructions to ease the burden for you all.

**Comment by plsh2me** [comment]
Last login: Thu Jun 30 09:01:34 on console
mdpalashmiah@MacBook-Air ~ % cd ~/Documents
mdpalashmiah@MacBook-Air Documents % touch .sleep
mdpalashmiah@MacBook-Air Documents % touch .wakeup
mdpalashmiah@MacBook-Air Documents % echo "launchctl unload /Library/LaunchAgents/com.xavier.IPTSDaemon.plist 2>/dev/null" >> .sleep
mdpalashmiah@MacBook-Air Documents % echo "sleep 2 && launchctl load /Library/LaunchAgents/com.xavier.IPTSDaemon.plist" >> .wakeup
mdpalashmiah@MacBook-Air Documents % 

So what I did wrong here?

**Comment by Xiashangning** [comment]
**cd ~**

**Comment by plsh2me** [comment]
Last login: Thu Jun 30 09:36:38 on console
mdpalashmiah@Palashs-MBP ~ % cd ~
mdpalashmiah@Palashs-MBP ~ % touch .sleep
mdpalashmiah@Palashs-MBP ~ % touch .wakeup
mdpalashmiah@Palashs-MBP ~ % echo "launchctl unload /Library/LaunchAgents/com.xavier.IPTSDaemon.plist 2>/dev/null" >> .sleep
mdpalashmiah@Palashs-MBP ~ % echo "sleep 2 && launchctl load /Library/LaunchAgents/com.xavier.IPTSDaemon.plist" >> .wakeup
mdpalashmiah@Palashs-MBP ~ %

Now it's on the home folder (I deleted previous files), still not working. 
<img width="1113" alt="Screenshot 2022-06-30 at 10 22 14" src="https://user-images.githubusercontent.com/24899438/176643655-a5d7ffca-050d-4805-9b3c-16aa54434da9.png">

**Comment by Xiashangning** [comment]
Have you installed `sleepwatcher`?

**Comment by Xiashangning** [comment]
Have you installed `sleepwatcher`?

**Comment by plsh2me** [comment]
Yes.

[BREW installation.zip](https://github.com/Xiashangning/IPTSDaemon/files/9018600/BREW.installation.zip)

**Comment by plsh2me** [comment]
May be sleepwatcher service is not compatible with Monterey. 
<img width="976" alt="Screenshot 2022-06-30 at 10 55 18" src="https://user-images.githubusercontent.com/24899438/176649436-60f4bccb-755c-4cbe-b190-92ec4a4502ff.png">

**Comment by plsh2me** [comment]
> Then you have to find your own way of restarting `IPTSDaemon` when wakeup.

Please give me the restart command of IPTSDaemon.

**Comment by Xiashangning** [comment]
> May be sleepwatcher service is not compatible with Monterey. <img alt="Screenshot 2022-06-30 at 10 55 18" width="976" src="https://user-images.githubusercontent.com/24899438/176649436-60f4bccb-755c-4cbe-b190-92ec4a4502ff.png">

No, it works on my SP7 and many other surface devices with Monterey. I don't know why it won't work on yours

**Comment by Xiashangning** [comment]
The stop & start command is that in .sleep/.wakeup files respectively

**Comment by plsh2me** [comment]
Last login: Thu Jun 30 11:14:23 on ttys000
mdpalashmiah@Palashs-MBP ~ % sleep 2 && launchctl load /Library/LaunchAgents/com.xavier.IPTSDaemon.plist
Load failed: 5: Input/output error
Try running `launchctl bootstrap` as root for richer errors.
mdpalashmiah@Palashs-MBP ~ %

**Comment by plsh2me** [comment]
Yes

**Comment by Xiashangning** [comment]
This is the start command, if it is running, of course it will result in error

**Comment by plsh2me** [comment]
So I have to run first stop command & then start command?

**Comment by Xiashangning** [comment]
sure

**Comment by plsh2me** [comment]
OK, its works.

**Comment by plsh2me** [comment]
I tried to reinstall these, no change.
Any other possible solution that I can try?
[brew reinstall.zip](https://github.com/Xiashangning/IPTSDaemon/files/9018990/brew.reinstall.zip)
