### ISSUE TITLE
Touch screen driver not found

### ISSUE THREAD

**Issue by ghost** [Xiashangning/IPTSDaemon#5]
Daemon installed successfully, but touchscreen won't work, manually ran the daemon shows "[error] Could not find IntelPreciseTouchStylusDriver".
Big Surface Version: 6.5
IPTSDaemon Version: 1.4
Device: Surface Pro 7 i5 8GB+256GB
ioreg and dmesg log attached.
[ioreg.txt](https://github.com/Xiashangning/IPTSDaemon/files/10891875/ioreg.txt)
[dmesg.txt](https://github.com/Xiashangning/IPTSDaemon/files/10891879/dmesg.txt)

**Comment by Xiashangning** [comment]
Issue duplicated #4

**Comment by Xiashangning** [comment]
Ur problem is most likely because u didn't update the loading config for BigSurface (there is a new plugin)
