### ISSUE TITLE
How to use IPTSDaemon on signin screen?

### ISSUE THREAD

**Issue by MaksimDeve** [Xiashangning/IPTSDaemon#6]
Hello! 
Everything works just awesome!!!
But i can't enter password, touchscreen start work after signin
How to resolve this isue?
Thx

**Comment by Xiashangning** [comment]
basically you need to start `IPTSDaemon` at launch screen. You can search for some method to do so.
If you find any way of starting this daemon at launch screen, please share it here so I will update my script.

**Comment by seven-of-eleven** [comment]
I'm pretty sure this has to do with where the the launch agent plist file is placed. From [here](https://support.apple.com/en-ca/guide/terminal/apdc6c1077b-5d5d-4d35-9c19-60f2397b2369/mac) or [here](https://ss64.com/osx/launchctl.html) if the location will determine when the daemon is started.

```
~/Library/LaunchAgents  (Per-user agents provided by the user. )
/Library/LaunchAgents    (Per-user agents provided by the administrator. )
/Library/LaunchDaemons  (System wide daemons provided by the administrator. )
/System/Library/LaunchAgents    (macOS Per-user agents. )
/System/Library/LaunchDaemons  (macOS System wide daemons.)
```

Based on this line in your script:
`sudo cp $DIR/com.xavier.IPTSDaemon.plist /Library/LaunchAgents`

The user needs to be logged in.  Changing the install location to `/Library/LaunchDaemons` should resolve the issue. 

**NOTE: I haven't tested this.** (I may have time over the weekend)

**Comment by liuson945** [comment]
其实有个简单的办法，关闭登录密码直接进入系统不是更好？
我觉得三楼的方法可行，但是有个问题，在登录输入密码界面macos没有屏幕键盘选项，只有进入系统后可以使用屏幕键盘！
我发现只要一旦进入系统，睡眠唤醒后再次输入密码界面，也可以调用屏幕键盘和触摸屏！

**Comment by seven-of-eleven** [comment]
@Xiashangning  I tried my suggestion above and the touchscreen now works at boot (login window). I simply moved the `com.xavier.IPTSDaemon.plist` file from `/Library/LaunchAgents/` to `/LibraryLaunchDaemons/`.

Note for the onscreen keyboard to show up on the login screen you need to change your Accessibility settings in the `System Preferences>Users & Groups>Login Options>Accessibility Options` put a checkbox on the `Accessibility Keyboard`.

Updating your script to install into that location should do the trick. Also note the `.sleep` and `.wakeup` files will also need to be updated in your guide. If I have time I'll update the script and send you a pull request.

For reference I'm on OC-0.8.2 and Monterey 12.4 at the moment.

Thanks for getting touch working!

**Comment by Xiashangning** [comment]
@seven-of-eleven Great, merged, will release a new version later
