### ISSUE TITLE
Surface Pro 7 Ventura no touchscreen 

### ISSUE THREAD

**Issue by sonvirgo** [Xiashangning/IPTSDaemon#6]
![Screen Shot 2023-03-12 at 1 32 10 PM](https://user-images.githubusercontent.com/10823037/224540732-28dc80eb-56c3-4145-90f9-6af29c824915.png)
[ioreg.zip](https://github.com/Xiashangning/IPTSDaemon/files/10950647/ioreg.zip)
[dsdt.aml.zip](https://github.com/Xiashangning/IPTSDaemon/files/10950650/dsdt.aml.zip)

**Comment by Xiashangning** [comment]
Issue duplicated #4 
Ur problem is most likely because u didn't update the loading config for BigSurface (there is a new plugin)
