### ISSUE TITLE
Load failed: 5: Input/output error Try running `launchctl bootstrap` as root for richer errors.

### ISSUE THREAD

**Issue by shiikoe** [Xiashangning/IPTSDaemon#7]
看ID应该是国人就用中文了x
大佬您好！我遇到了这个问题，安装的系统是12.5，此前IPTSDaemon一直无法启动，提示launchctl不能运行root权限命令，然后我就直接试了一下sudo IPTSDaemon，发现触摸屏好使。
本来就打算每次开机都打一下命令算了，但是为了折腾读卡器驱动重启几次后突然就直接找不到设备了。我没有改OC配置，只是加载了读卡器的kext，然后触摸屏就找不到了。
并且读卡器也并没有驱动上。
跪求解惑orz

**Comment by shiikoe** [comment]
设备是Surface Pro7 i5-1035G4

**Comment by shiikoe** [comment]
前面的问题重新安装系统后解决了。但是依然还是一样的，直接执行脚本后触摸没反应，一条条运行发现最后一条报错：
Load failed: 5: Input/output error Try running launchctl bootstrap as root for richer errors.
加上sudo之后可以正常运行，但是重启后并不会生效。

配置了sleepwatcher也无效。

跪求大佬指点一下。为前面我自己错误的issue道歉

**Comment by shiikoe** [comment]
哈哈！问题解决了。系统是12.5，只需要讲脚本倒数五行修改一下：
sudo cp $DIR/com.xavier.IPTSDaemon.plist /Library/LaunchDaemons
sudo chmod 644 /Library/LaunchDaemons/com.xavier.IPTSDaemon.plist
sudo chown root:wheel /Library/LaunchDaemons/com.xavier.IPTSDaemon.plist
sudo xattr -d com.apple.quarantine /Library/LaunchDaemons/com.xavier.IPTSDaemon.plist 2>/dev/null

sudo launchctl load /Library/LaunchDaemons/com.xavier.IPTSDaemon.plist

12系统需要用Daemons才行，不能是agents模式。这样就可以开机启动了。
感谢大佬提供的驱动 非常Nice，吃灰的Pro7再一次有了点作用！

**Comment by Xiashangning** [comment]
好的，过段时间会发布修改过的新版本
