### ISSUE TITLE
Some files or directories cannot be found

### ISSUE THREAD

**Issue by BelugaChase** [Xiashangning/IPTSDaemon#8]
like this
<img width="1368" alt="截屏2023-03-23 01 32 37" src="https://user-images.githubusercontent.com/117560335/226990706-a256373a-388f-44fc-86c1-5871c7e6e7ae.png">
<img width="697" alt="截屏2023-03-23 01 34 21" src="https://user-images.githubusercontent.com/117560335/226990720-5316abeb-e10f-4c99-9cbd-a240c832dc88.png">
I am using Surface Pro 7,the all plugin versions are the latest.

**Comment by Xiashangning** [comment]
Oh, this is because /usr/local/lib isn't present, you can try `sudo mkdir /usr/local/lib` then run this script. This will be fixed in next release
