### ISSUE TITLE
IPTSDaemon not installing properly, suggests I use launchctl bootstrap? (Surface Pro 2017)

### ISSUE THREAD

**Issue by Hardfg5000** [Xiashangning/IPTSDaemon#9]
Hello, I have been trying to the touchscreen on my Surface pro 2017 macOS Monterey hackintosh using your big surface kext, but some reason, when I try and load the script, this appears:

cp: /Users/harryevans/Downloads/IPTSDaemon-main/IPTSDaemon/IPTSDaemon: No such file or directory
chmod: /usr/local/bin/IPTSDaemon: No such file or directory
chown: /usr/local/bin/IPTSDaemon: No such file or directory
cp: /Users/harryevans/Downloads/IPTSDaemon-main/IPTSDaemon/ipts_config: No such file or directory
Warning: Expecting a LaunchAgents path since the command was ran as user. Got LaunchDaemons instead.
`launchctl bootstrap` is a recommended alternative.

I have cd'd into the folder where the script is, like suggested in a previous issue. I tried the release folder and the dev folder with both recommending launchctl bootstrap. What am I doing wrong?

**Comment by seven-of-eleven** [comment]
Did you download the release and run the script or download the code? There should be no issue running the script from within the release folder. If you downloaded the code then it will error out.

**Comment by Hardfg5000** [comment]
I did that and idk if it worked because it didn't give anything to tell me it was successful. Does this mean it worked?
Regardless of it, the touchscreen doesn't work. I don't believe I set up SSDT's properly but because the guide is so vague, idk how it all works

**Comment by seven-of-eleven** [comment]
You can check if it worked by examining the contents of the folders in the terminal:

`ls /usr/local/bin/|grep IPTSDaemon' and see `IPTSDaemon` is listed
`ls /usr/local/` and see if `ipts_config` is listed
`ls /Library/LaunchAgents/` and see if `com.xavier.IPTSDaemon.plist` is listed.

If all three show the files then the script completed successfully. Did you install Homebrew and required files prior to running the script?

**Comment by Hardfg5000** [comment]
They all seem to be there and installed the script and Homebrew after. By "required files", is there a step I missed?

**Comment by seven-of-eleven** [comment]
You didn't miss any files. Poorly worded on my part. 

One final check you can do is `sudo launchctl list | grep -i IPTS`. If you get an output (mine returns `104    0      com.xavier.IPTSDaemon` yours number may be different) then IPTSDaemon is running and you likely have other issues with your EFI setup/config unrelated to this.

If you don't get a return then IPSD isn't running. You can try and run 
` sudo launchctl load /Library/LaunchAgents/com.xavier.IPTSDaemon.plist`
to (re)start it.

**Comment by seven-of-eleven** [comment]
@Hardfg5000 one final note regarding the guide. This section:
```
cd ~
touch .sleep
touch .wakeup
echo "launchctl unload /Library/LaunchDaemons/com.xavier.IPTSDaemon.plist 2>/dev/null" >> .sleep
echo "sleep 2 && launchctl load /Library/LaunchDaemons/com.xavier.IPTSDaemon.plist" >> .wakeup
```
is for the upcoming release.

### You'll want to use
```
cd ~
touch .sleep
touch .wakeup
echo "launchctl unload /Library/LaunchAgents/com.xavier.IPTSDaemon.plist 2>/dev/null" >> .sleep
echo "sleep 2 && launchctl load /Library/LaunchAgents/com.xavier.IPTSDaemon.plist" >> .wakeup
```
which is for release 1.1

**Comment by Xiashangning** [comment]
@Hardfg5000 double click on IPTSDaemon app to run it manually, and tell me what is your output

**Comment by Xiashangning** [comment]
@seven-of-eleven If you move IPTSDaemon to LauchDaemons folder, then it should be executed with sudo, so in the script those two commands load/unload for LauchDaemons/.plist should start with sudo. Then here comes a problem that sleepwatcher cannot execute command with sudo, so IPTSDaemon will fail to function after wake up from sleep. I am investigating how to maintain the functionality throughout the sleep/wake-up  schedule so finally we can get rid of this sleepwatcher trick.

**Comment by Hardfg5000** [comment]
Xiashangning:
Users/Me/Downloads/IPTSDaemon/IPTSDaemon ; exit;
[17:41:05.533] [error] Could not find IntelPreciseTouchStylusDriver!

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

Guess it's missing a driver or something.

seven-of-eleven:
The output of the first command was: -	1	com.xavier.IPTSDaemon
Confused, I did the restart command and it said:

Warning: Expecting a LaunchDaemons path since the command was ran as root. Got LaunchAgents instead.
`launchctl bootstrap` is a recommended alternative.
/Library/LaunchAgents/com.xavier.IPTSDaemon.plist: service already loaded
Load failed: 17: File exists

It seems to be loaded already?

**Comment by seven-of-eleven** [comment]
@Hardfg5000 Yes it does seem to be loaded. You may be missing a kext? Check against [Xiashangning's EFI folder](https://github.com/Xiashangning/SurfacePro7Opencore) for reference.

Best of luck.

**Comment by slayer8197** [comment]
also getting this too

according to launchctl documentation load and unload are legacy and not used anymore. Im on Monterey 12.5 fyi

Warning: Expecting a LaunchDaemons path since the command was ran as root. Got LaunchAgents instead.
`launchctl bootstrap` is a recommended alternative.

**Comment by liuson945** [comment]
宁总，你只是更新了原代码里的install_daemon.sh内容，下载的zip文件里面没有更新，出现问题的是下载的zip文件，我没有出现问题

**Comment by Xiashangning** [comment]
@Hardfg5000 You have installed IPTSDaemon correctly, the problem is that the kernel space driver `IntelPreciseTouchStylusDriver` is missing. I need your ioreg file.

**Comment by Hardfg5000** [comment]
I assume this is it?
https://drive.google.com/file/d/1PhsdlAaU5hYd9hqkj8Pn4yEnwXVXMdy0/view?usp=sharing
(Had to google drive it because it didn't let me drop here)

**Comment by Xiashangning** [comment]
Ok, now i need you first install `DebugEnhancer.kext` and then attach the output of `sudo dmesg | grep -E "SurfaceM|IntelP"`

**Comment by Hardfg5000** [comment]
I somehow never got any output. I put the kext into the kext folder on my USB then added it to config.plist the same way as the big surface kexts. Do I have to install it on the system itself in the /L/E folder?

**Comment by Xiashangning** [comment]
Firstly, do you have the latest version of BigSurface (6.1 pre-release version)?
If so, then it is indeed strange. Try this one `sudo dmesg | grep -E "SurfaceS|SurfaceB|SurfaceH|SurfaceM|IntelP"`

**Comment by Hardfg5000** [comment]
I am on 6.0. I didn't realize there was a 6.1 pre-release until after I installed. Should I update?
The command did output stuff but it was so long, I put it into a textedit document instead:
https://drive.google.com/file/d/1Z-b5CzN3OniTYV6gYMw4QLcuTNkAJS65/view?usp=sharing
(again, google drive cuz GitHub doesn't support the file type)

**Comment by Hardfg5000** [comment]
uhhhhhh I updated to 6.1 and touchscreen works now... Interesting. It works, but glitches out.For example, Sometimes I tap and it goes to the top left corner and clicks there instead for no reason. There is no issue with my surface. Sometimes, a top double clicks as well and I cannot enter mission control launchpad etc. The gestures works, but it just goes back and cancels itself out for some reason. Can this be adjusted or do I need to live with it?

**Comment by Xiashangning** [comment]
From your log we can see that despite your battery works, the communication between the driver and the device is very ineffective (always has error in transmission of both sides). Attach your DSDT and I will have a look when I am free.
For your touchscreen, SP7 has no glitches at all. Give me the output of `sudo dmesg | grep -E "SurfaceM|IntelP"`. Now there should be some output

**Comment by Xiashangning** [comment]
I need DSDT, not SSDT

**Comment by Xiashangning** [comment]
Please try this build, and send me `sudo dmesg | grep SurfaceS`
[BigSurface.kext.zip](https://github.com/Xiashangning/IPTSDaemon/files/9217716/BigSurface.kext.zip)

**Comment by Hardfg5000** [comment]
Here's the log:

[    1.004582]: SurfaceSerialHubDriver::Found valid UART bus and GPIO interrupt!
[    1.016092]: SurfaceSerialHubDriver::Got GPIO Controller! VoodooGPIOSunrisePointLP
[    1.033428]: SurfaceSerialHubDriver::Got UART Controller! VoodooUARTController
[    1.133438]: SurfaceSerialHubDriver::Surface Serial Hub found!
[    1.184812]: SurfaceSerialHubDriver::Warning, NAK received! Resending all pending messages!
[    1.187319]: SurfaceSerialHubDriver::SAM version 59.62253.1
[    1.337484]: SurfaceSerialHubDriver::Timeout waiting for response
[    1.337498]: SurfaceSerialHubDriver::Unexpected response from D0-entry notification
[    1.339362]: SurfaceSerialHubDriver::Surface Battery nub published!
[    1.489694]: SurfaceSerialHubDriver::Timeout waiting for response
[    1.639838]: SurfaceSerialHubDriver::Timeout waiting for response
[    1.639855]: SurfaceSerialHubDriver::Failed to attach Surface HID nub! Ignore this if you don't need this
[   31.346118]: SurfaceSerialHubDriver::Warning, NAK received! Resending all pending messages!
[   31.456667]: SurfaceSerialHubDriver::data length error!
[   31.456677]: SurfaceSerialHubDriver::msg dump: length: 64
[   31.456680]: SurfaceSerialHubDriver::aa 55 80 7f 00 8d e4 ed 80 02 00 01 01 29 00 02 
[   31.456685]: SurfaceSerialHubDriver::00 00 00 00 00 c8 af 00 00 a8 8e 00 00 01 00 00 
[   31.456689]: SurfaceSerialHubDriver::00 92 1d 00 00 5e 1a 00 00 46 05 00 00 28 01 00 
[   31.456693]: SurfaceSerialHubDriver::00 e8 03 00 00 ff ff ff ff ff ff ff ff e8 03 00 
[   31.457956]: SurfaceSerialHubDriver::data length error!
[   31.457967]: SurfaceSerialHubDriver::msg dump: length: 64
[   31.457970]: SurfaceSerialHubDriver::aa 55 80 7f 00 8d e4 ed 80 02 00 01 01 29 00 02 
[   31.457975]: SurfaceSerialHubDriver::00 00 00 00 00 c8 af 00 00 a8 8e 00 00 01 00 00 
[   31.457979]: SurfaceSerialHubDriver::00 92 1d 00 00 5e 1a 00 00 46 05 00 00 28 01 00 
[   31.457984]: SurfaceSerialHubDriver::00 e8 03 00 00 ff ff ff ff ff ff ff ff e8 03 00 
[   31.459244]: SurfaceSerialHubDriver::data length error!
[   31.459253]: SurfaceSerialHubDriver::msg dump: length: 64
[   31.459256]: SurfaceSerialHubDriver::aa 55 80 7f 00 8d e4 ed 80 02 00 01 01 29 00 02 
[   31.459261]: SurfaceSerialHubDriver::00 00 00 00 00 c8 af 00 00 a8 8e 00 00 01 00 00 
[   31.459265]: SurfaceSerialHubDriver::00 92 1d 00 00 5e 1a 00 00 46 05 00 00 28 01 00 
[   31.459269]: SurfaceSerialHubDriver::00 e8 03 00 00 ff ff ff ff ff ff ff ff e8 03 00 
[   31.460491]: SurfaceSerialHubDriver::data length error!
[   31.460500]: SurfaceSerialHubDriver::msg dump: length: 64
[   31.460503]: SurfaceSerialHubDriver::aa 55 80 7f 00 8d e4 ed 80 02 00 01 01 29 00 02 
[   31.460508]: SurfaceSerialHubDriver::00 00 00 00 00 c8 af 00 00 a8 8e 00 00 01 00 00 
[   31.460513]: SurfaceSerialHubDriver::00 92 1d 00 00 5e 1a 00 00 46 05 00 00 28 01 00 
[   31.460518]: SurfaceSerialHubDriver::00 e8 03 00 00 ff ff ff ff ff ff ff ff e8 03 00 
[   31.498913]: SurfaceSerialHubDriver::Timeout waiting for response
[   31.500107]: SurfaceSerialHubDriver::data length error!
[   31.500117]: SurfaceSerialHubDriver::msg dump: length: 64
[   31.500119]: SurfaceSerialHubDriver::aa 55 80 7f 00 8d e4 ed 80 02 00 01 01 29 00 02 
[   31.500124]: SurfaceSerialHubDriver::00 00 00 00 00 c8 af 00 00 a8 8e 00 00 01 00 00 
[   31.500128]: SurfaceSerialHubDriver::00 92 1d 00 00 5e 1a 00 00 46 05 00 00 28 01 00 
[   31.500132]: SurfaceSerialHubDriver::00 e8 03 00 00 ff ff ff ff ff ff ff ff e8 03 00 
[   31.549216]: SurfaceSerialHubDriver::Timeout, trial count: 2
[   31.550356]: SurfaceSerialHubDriver::Warning, no pending command found for seq_id 8
[   31.850263]: Sandbox apply: securityd_servic[351] <bytes>SurfaceSerialHubDriver::Warning, NAK received! Resending all pending messages!
[   32.105508]: SurfaceSerialHubDriver::data length error!
[   32.105544]: SurfaceSerialHubDriver::msg dump: length: 64
[   32.105548]: SurfaceSerialHubDriver::aa 55 80 7f 00 8f a6 cd 80 02 00 01 01 2c 00 02 
[   32.105555]: SurfaceSerialHubDriver::00 00 00 00 00 c8 af 00 00 a8 8e 00 00 01 00 00 
[   32.105561]: SurfaceSerialHubDriver::00 92 1d 00 00 5e 1a 00 00 46 05 00 00 28 01 00 
[   32.105567]: SurfaceSerialHubDriver::00 e8 03 00 00 ff ff ff ff ff ff ff ff e8 03 00 
[   32.152950]: SurfaceSerialHubDriver::Timeout waiting for response
[   32.212625]: SurfaceSerialHubDriver::data length error!
[   32.212649]: SurfaceSerialHubDriver::msg dump: length: 111
[   32.212653]: SurfaceSerialHubDriver::aa 55 80 7f 00 8f a6 cd 80 02 00 01 01 2c 00 02 
[   32.212657]: SurfaceSerialHubDriver::00 00 00 00 00 c8 af 00 00 a8 8e 00 00 01 00 00 
[   32.212661]: SurfaceSerialHubDriver::00 92 1d 00 00 5e 1a 00 00 46 05 00 00 28 01 00 
[   32.212665]: SurfaceSerialHubDriver::00 e8 03 00 00 ff ff ff ff ff ff ff ff e8 03 00 
[   32.212669]: SurfaceSerialHubDriver::00 e8 03 00 00 0a 00 00 00 0a 00 00 00 4d 31 30 
[   32.212673]: SurfaceSerialHubDriver::30 39 31 36 38 00 00 00 00 00 00 00 00 00 00 00 
[   32.212677]: SurfaceSerialHubDriver::00 00 30 30 31 36 37 30 37 37 33 35 00 4c 49 00 
[   32.214140]: SurfaceSerialHubDriver::data length error!
[   32.214151]: SurfaceSerialHubDriver::msg dump: length: 64
[   32.214154]: SurfaceSerialHubDriver::aa 55 80 7f 00 8f a6 cd 80 02 00 01 01 2c 00 02 
[   32.214160]: SurfaceSerialHubDriver::00 00 00 00 00 c8 af 00 00 a8 8e 00 00 01 00 00 
[   32.214166]: SurfaceSerialHubDriver::00 92 1d 00 00 5e 1a 00 00 46 05 00 00 28 01 00 
[   32.214171]: SurfaceSerialHubDriver::00 e8 03 00 00 ff ff ff ff ff ff ff ff e8 03 00 
[   32.655228]: SurfaceSerialHubDriver::data length error!
[   32.655236]: SurfaceSerialHubDriver::msg dump: length: 64
[   32.655244]: SurfaceSerialHubDriver::aa 55 80 7f 00 8f a6 cd 80 02 00 01 01 2c 00 02 
[   32.655249]: SurfaceSerialHubDriver::00 00 00 00 00 c8 af 00 00 a8 8e 00 00 01 00 00 
[   32.655253]: SurfaceSerialHubDriver::00 92 1d 00 00 5e 1a 00 00 46 05 00 00 28 01 00 
[   32.655258]: SurfaceSerialHubDriver::00 e8 03 00 00 ff ff ff ff ff ff ff ff e8 03 00 
[   32.704612]: SurfaceSerialHubDriver::Timeout, trial count: 2
[   32.705831]: SurfaceSerialHubDriver::Warning, NAK received! Resending all pending messages!
[   32.795793]: Sandbox apply: trustd[363] <bytes>SurfaceSerialHubDriver::data length error!
[   32.810205]: SurfaceSerialHubDriver::msg dump: length: 64
[   32.810209]: SurfaceSerialHubDriver::aa 55 80 7f 00 91 59 3e 80 02 00 01 01 2e 00 02 
[   32.810213]: SurfaceSerialHubDriver::00 00 00 00 00 c8 af 00 00 a8 8e 00 00 01 00 00 
[   32.810217]: SurfaceSerialHubDriver::00 92 1d 00 00 5e 1a 00 00 46 05 00 00 28 01 00 
[   32.810221]: SurfaceSerialHubDriver::00 e8 03 00 00 ff ff ff ff ff ff ff ff e8 03 00 
[   32.811466]: SurfaceSerialHubDriver::data length error!
[   32.811473]: SurfaceSerialHubDriver::msg dump: length: 83
[   32.811476]: SurfaceSerialHubDriver::aa 55 80 7f 00 91 59 3e 80 02 00 01 01 2e 00 02 
[   32.811480]: SurfaceSerialHubDriver::00 00 00 00 00 c8 af 00 00 a8 8e 00 00 01 00 00 
[   32.811485]: SurfaceSerialHubDriver::00 92 1d 00 00 5e 1a 00 00 46 05 00 00 28 01 00 
[   32.811488]: SurfaceSerialHubDriver::00 e8 03 00 00 ff ff ff ff ff ff ff ff e8 03 00 
[   32.811492]: SurfaceSerialHubDriver::00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[   32.811496]: SurfaceSerialHubDriver::00 07 f6 00 00 00 00 00 00 00 00 00 00 00 00 00 
[   32.812740]: SurfaceSerialHubDriver::data length error!
[   32.812748]: SurfaceSerialHubDriver::msg dump: length: 64
[   32.812751]: SurfaceSerialHubDriver::aa 55 80 7f 00 91 59 3e 80 02 00 01 01 2e 00 02 
[   32.812755]: SurfaceSerialHubDriver::00 00 00 00 00 c8 af 00 00 a8 8e 00 00 01 00 00 
[   32.812759]: SurfaceSerialHubDriver::00 92 1d 00 00 5e 1a 00 00 46 05 00 00 28 01 00 
[   32.812763]: SurfaceSerialHubDriver::00 e8 03 00 00 ff ff ff ff ff ff ff ff e8 03 00 
[   32.813967]: SurfaceSerialHubDriver::data length error!
[   32.813974]: SurfaceSerialHubDriver::msg dump: length: 64
[   32.813976]: SurfaceSerialHubDriver::aa 55 80 7f 00 91 59 3e 80 02 00 01 01 2e 00 02 
[   32.813980]: SurfaceSerialHubDriver::00 00 00 00 00 c8 af 00 00 a8 8e 00 00 01 00 00 
[   32.813985]: SurfaceSerialHubDriver::00 92 1d 00 00 5e 1a 00 00 46 05 00 00 28 01 00 
[   32.813990]: SurfaceSerialHubDriver::00 e8 03 00 00 ff ff ff ff ff ff ff ff e8 03 00 
[   32.829403]: Sandbox apply: trustdFileHelper[364] <bytes>Sandbox apply: tccd[357] <bytes>SurfaceSerialHubDriver::Timeout waiting for response
[   33.016310]: Sandbox apply: com.apple.speech[365] <bytes>SurfaceSerialHubDriver::data length error!
[   33.358976]: SurfaceSerialHubDriver::msg dump: length: 64
[   33.358979]: SurfaceSerialHubDriver::aa 55 80 7f 00 91 59 3e 80 02 00 01 01 2e 00 02 
[   33.358984]: SurfaceSerialHubDriver::00 00 00 00 00 c8 af 00 00 a8 8e 00 00 01 00 00 
[   33.358988]: SurfaceSerialHubDriver::00 92 1d 00 00 5e 1a 00 00 46 05 00 00 28 01 00 
[   33.358992]: SurfaceSerialHubDriver::00 e8 03 00 00 ff ff ff ff ff ff ff ff e8 03 00 
[   33.408306]: SurfaceSerialHubDriver::Timeout, trial count: 2
[   33.409510]: SurfaceSerialHubDriver::Warning, NAK received! Resending all pending messages!
[   33.513534]: SurfaceSerialHubDriver::data length error!
[   33.513574]: SurfaceSerialHubDriver::msg dump: length: 64
[   33.513577]: SurfaceSerialHubDriver::aa 55 80 7f 00 93 1b 1e 80 02 00 01 01 30 00 02 
[   33.513582]: SurfaceSerialHubDriver::00 00 00 00 00 c8 af 00 00 a8 8e 00 00 01 00 00 
[   33.513587]: SurfaceSerialHubDriver::00 92 1d 00 00 5e 1a 00 00 46 05 00 00 28 01 00 
[   33.513591]: SurfaceSerialHubDriver::00 e8 03 00 00 ff ff ff ff ff ff ff ff e8 03 00 
[   33.516162]: SurfaceSerialHubDriver::data length error!
[   33.516171]: SurfaceSerialHubDriver::msg dump: length: 55
[   33.516173]: SurfaceSerialHubDriver::aa 55 80 7f 00 93 1b 1e 80 02 00 01 01 30 00 02 
[   33.516178]: SurfaceSerialHubDriver::00 00 00 00 00 c8 af 00 00 a8 8e 00 00 01 00 00 
[   33.516182]: SurfaceSerialHubDriver::00 92 1d 00 00 5e 1a 00 00 46 05 00 00 28 01 00 
[   33.516186]: SurfaceSerialHubDriver::00 e8 03 00 00 ff ff 00 00 00 00 00 00 00 00 00 
[   34.416289]: Sandbox apply: Safari[360] <bytes>SurfaceSerialHubDriver::Warning, NAK received! Resending all pending messages!
[   35.919877]: Sandbox apply: iconservicesagen[404] <bytes>Sandbox apply: contactsd[402] <bytes>Sandbox apply: CVMServer[408] <bytes>Sandbox apply: fontworker[383] <bytes>Sandbox apply: distnoted[397] <bytes>Sandbox apply: ScreenTimeAgent[396] <bytes>SurfaceSerialHubDriver::Warning, NAK received! Resending all pending messages!
[   36.619049]: Sandbox apply: AudioComponentRe[410] <bytes>Sandbox apply: com.apple.access[409] <bytes>Sandbox apply: siriactionsd[395] <bytes>1 duplicate report for Sandbox: itunescloudd(359) deny(1) user-preference-read com.apple.mediaplaybackcoreSandbox: siriactionsd(395) deny(1) file-read-data /Library/Preferences/com.apple.networkd.plistSandbox apply: com.apple.Safari[390] <bytes>Sandbox apply: CalendarAgent[399] <bytes>1 duplicate report for Sandbox: siriactionsd(395) deny(1) file-read-data /Library/Preferences/com.apple.networkd.plistSandbox: secd(384) deny(1) user-preference-write secdresponsibility for com.apple.dock.e[418] set to that of com.apple.dock.e[418]: /System/Library/CoreServices/Dock.app/Contents/XPCServices/com.apple.dock.extra.xpc/Contents/MacOS/com.apple.dock.extraSandbox apply: bird[407] <bytes>Sandbox apply: CarbonComponentS[416] <bytes>SurfaceSerialHubDriver::Warning, NAK received! Resending all pending messages!
[   37.615377]: Sandbox apply: AMPDeviceDiscove[403] <bytes>Sandbox apply: com.apple.quickl[419] <bytes>1 duplicate report for Sandbox: secd(384) deny(1) user-preference-write secdSandbox: com.apple.Safari(390) deny(1) user-preference-read kCFPreferencesAnyApplicationSandbox apply: com.apple.WebKit[411] <bytes>2 duplicate reports for Sandbox: com.apple.Safari(390) deny(1) user-preference-read kCFPreferencesAnyApplicationSandbox: com.apple.WebKit(411) allow syscall-mach 21Sandbox: com.apple.WebKit(411) deny(1) mach-lookup com.apple.distributed_notifications@Uv3Sandbox: com.apple.WebKit(411) deny(1) mach-lookup com.apple.tccd.systemSurfaceSerialHubDriver::Warning, NAK received! Resending all pending messages!
[   64.693445]: 3 duplicate reports for Sandbox: contentlinkingd(553) deny(1) user-preference-read kCFPreferencesAnyApplicationSandbox: secd(384) deny(1) user-preference-write secdSandbox apply: com.apple.Safari[556] <bytes>Sandbox: com.apple.Safari(556) deny(1) mach-lookup com.apple.touchbarserver.migSandbox: networkservicepr(414) deny(1) ipc-posix-shm-write-create com.apple.AppleDatabaseChangedSurfaceSerialHubDriver::Warning, NAK received! Resending all pending messages!
[   94.281424]: Sandbox: SafariBookmarksS(413) deny(1) user-preference-read com.apple.CloudKit2 duplicate reports for Sandbox: SafariBookmarksS(413) deny(1) user-preference-read com.apple.CloudKitSandbox: remindd(498) deny(1) file-read-data /Library/Preferences/com.apple.networkd.plistSandbox: suggestd(459) deny(1) mach-lookup com.apple.progressdSandbox: remindd(498) deny(1) file-read-data /Library/Preferences/com.apple.networkd.plistSurfaceSerialHubDriver::Warning, NAK received! Resending all pending messages!
[  125.603638]: SurfaceSerialHubDriver::Warning, NAK received! Resending all pending messages!
[  155.614129]: SurfaceSerialHubDriver::Warning, NAK received! Resending all pending messages!
[  185.625106]: SurfaceSerialHubDriver::Warning, NAK received! Resending all pending messages!
[  215.636207]: SurfaceSerialHubDriver::Warning, NAK received! Resending all pending messages!
[  245.648539]: SurfaceSerialHubDriver::Warning, NAK received! Resending all pending messages!
[  275.660124]: SurfaceSerialHubDriver::Warning, NAK received! Resending all pending messages!
[  305.136048]: Sandbox apply: mdworker_shared[836] <bytes>SurfaceSerialHubDriver::Warning, NAK received! Resending all pending messages!
[  335.683885]: SurfaceSerialHubDriver::Warning, NAK received! Resending all pending messages!
[  395.706681]: SurfaceSerialHubDriver::Warning, NAK received! Resending all pending messages!
[  425.718632]: SurfaceSerialHubDriver::Warning, NAK received! Resending all pending messages!
[  455.730289]: SurfaceSerialHubDriver::Warning, NAK received! Resending all pending messages!
[  485.742715]: SurfaceSerialHubDriver::Warning, NAK received! Resending all pending messages!
[  515.570836]: Sandbox: com.apple.WebKit(1083) deny(1) mach-lookup com.apple.analyticsdSandbox: com.apple.WebKit(1083) deny(1) file-read-data /Library/Application Support/CrashReporter/Su
[dsdt.aml.zip](https://github.com/Xiashangning/IPTSDaemon/files/9219453/dsdt.aml.zip)
bmitDiagInfo.domainsSurfaceSerialHubDriver::Warning, NAK received! Resending all pending messages!

The kext does perform better, but any gestures (mission control etc) still doesn't go through. The DSDT is attached if you still need it.

**Comment by Xiashangning** [comment]
Your touchscreen problem is solved by the new release, please try it (also with the new release of BigSurface)

**Comment by Hardfg5000** [comment]
sorry for the late response, but the touchscreen works very well now. Thank you so much for creating BigSurface and making touchscreen work. This makes a surface hackintosh much more viable as a daily driver as before and it's amazing!

**Comment by seven-of-eleven** [comment]
For reference I updated to BigSurface-6.1 and IPTSDaemon-1.2 on my Surface Pro 7. Everything seems to be working great. Thanks!
